### ISSUE TITLE
Add tagged version?

### ISSUE THREAD

**Issue by bkosborne** [audiolabs/bibtexparser#4]
Hello! I wonder if you could please just add a tagged version to this repo? Anyone that requires this project via composer means that they have to require it as "dev-master" instead of "1.0.0", which means composer will clone the repo and checkout the latest version of master. The problem is that Github puts API limits on cloning and sometimes users will be prompted for entering a personal Github access token. It's just a lot of work for something we can avoid if there's a tagged version, since then would let composer download the .zip file that Github produces.

Thanks!

**Comment by fzalkow** [comment]
Hi! Thanks for this suggestion. I just created a tag.
https://github.com/audiolabs/bibtexparser/releases/tag/1.0.0
